[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "*"
[[redirects]]
  from = "/*"
  to = "homeaccesscenterapi.vercel.app/:splat"
  status = 200
  force = true
